###
GET http://localhost:9000/api/jusers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0OTI0NzY2LCJleHAiOjE3NTQ5MjY1NjZ9.3sXA8qQ9lZIRp3jVquUQld_nXslFnIqSFFvZIfGqV9Q


###
GET http://localhost:9000/api/jusers/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0OTI0NzY2LCJleHAiOjE3NTQ5MjY1NjZ9.3sXA8qQ9lZIRp3jVquUQld_nXslFnIqSFFvZIfGqV9Q


###
POST http://localhost:9000/api/jusers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0OTI0NzY2LCJleHAiOjE3NTQ5MjY1NjZ9.3sXA8qQ9lZIRp3jVquUQld_nXslFnIqSFFvZIfGqV9Q
Content-Type: application/json

{
    "correo": "fabian@nursrl.com",
    "clave": "12345", 
    "nombre": "Fabian Peña", 
    "tipo": "usuario", 
    "estado": "A"
}


###
PUT http://localhost:9000/api/jusers/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0OTI0NzY2LCJleHAiOjE3NTQ5MjY1NjZ9.3sXA8qQ9lZIRp3jVquUQld_nXslFnIqSFFvZIfGqV9Q
Content-Type: application/json

{
    "correo": "leonardo@nursrl.com",
    "nombre": "Leonardo Peña", 
    "tipo": "admin", 
    "clave": "12345" 
}


###
DELETE  http://localhost:9000/api/jusers/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0OTI0NzY2LCJleHAiOjE3NTQ5MjY1NjZ9.3sXA8qQ9lZIRp3jVquUQld_nXslFnIqSFFvZIfGqV9Q
